# Generated by Django 4.1 on 2022-08-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainee",
            name="age",
        ),
        migrations.RemoveField(
            model_name="trainee",
            name="height",
        ),
    ]
