# Generated by Django 4.0.5 on 2022-08-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='vedio',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(default='', upload_to='exercises/'),
        ),
    ]
