# Generated by Django 4.0.5 on 2022-09-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='describtion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exerciseitem',
            name='date',
            field=models.DateField(default='2022-09-01'),
        ),
        migrations.AddField(
            model_name='trainee',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trainee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(default='static/exercise.png', upload_to='exercises/'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='age',
            field=models.IntegerField(blank=True, default=25, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='blood_type',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='O+', max_length=250),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='height',
            field=models.IntegerField(default=165, null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainees/'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='weight',
            field=models.IntegerField(default=70, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/'),
        ),
    ]
