# Generated by Django 4.0.5 on 2022-08-28 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_rename_vedio_exercise_video_alter_exercise_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.IntegerField()),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='fitness.exercise')),
            ],
        ),
        migrations.DeleteModel(
            name='Step',
        ),
    ]
