# Generated by Django 4.1 on 2022-08-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0002_remove_trainee_age_remove_trainee_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="age",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="experience",
            field=models.IntegerField(blank=True),
        ),
    ]
