# Generated by Django 4.1 on 2022-08-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0003_alter_trainer_age_alter_trainer_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
