# Generated by Django 4.1 on 2022-08-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0004_alter_trainer_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="experience",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
