# Generated by Django 4.0.5 on 2022-09-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_trainee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(help_text='this is the string id for this exercise, it must be unique!', max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(default='static/exercise.png', upload_to='exercises/'),
        ),
    ]
