# Generated by Django 4.0.5 on 2022-09-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_exercise_slug_alter_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(editable=False, max_length=300, unique=True),
        ),
    ]
