# Generated by Django 4.0.5 on 2022-08-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_exerciseitem_reps_exerciseitem_sets_delete_setitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseitem',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
