# Generated by Django 4.0.5 on 2022-08-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_exerciseitem_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseitem',
            name='time',
            field=models.TimeField(default='10:00'),
        ),
    ]
