# Generated by Django 4.0.5 on 2022-08-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_exerciseitem_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionitem',
            name='trainee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='fitness.trainee'),
        ),
    ]
