# Generated by Django 4.0.5 on 2022-09-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=300, unique=True),
        ),
    ]
