# Generated by Django 4.0.5 on 2022-08-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_alter_subscriptionitem_trainee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionitem',
            name='start_date',
            field=models.DateField(),
        ),
    ]
