# Generated by Django 4.0.5 on 2022-09-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_alter_exercise_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='describtion',
            new_name='description',
        ),
        migrations.AddField(
            model_name='trainee',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='trainer',
            name='bio',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video',
            field=models.URLField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='image',
            field=models.ImageField(null=True, upload_to='trainees/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(null=True, upload_to='trainers/'),
        ),
    ]
