# Generated by Django 4.0.5 on 2022-08-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_alter_subscriptionitem_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='image',
            field=models.ImageField(default='', upload_to='trainees/'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='', upload_to='trainers/'),
        ),
    ]
