# Generated by Django 4.0.5 on 2022-09-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_rename_describtion_subscription_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='blood_type',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB-')], default='O+', max_length=250),
        ),
    ]
