# Generated by Django 4.0.5 on 2022-09-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_alter_trainee_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='gender',
            field=models.CharField(choices=[('Gender', 'Gender'), ('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
